@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0
hide circle
hide methods

class Customer{
    NIF
    name
    address
    phone
    email
    category
    orders
}

class Product{

}

class Product_Variant{
    size
    colour
}

class Factory{
    type_of_factory
    safety
    efficiency
    space
}

class Factory_Type{
    type
}

class Raw_Material{

}

class Plant_Floor{
    stations
}

class Station{
    type_of_station
    type_of_industry
}

class Station_Type{
    type
}

class Industry_Type{
    industry_types
    operations
}

class Operation{
    Operations_names
}

class Production_Plan{
    orders
    begin_date
    end_date
}

class Order{
    order_ID
    customer_ID
    products
    delivery_date
    location
}

class Category_Customer{
    category
}

class Production_Order{

}


Factory "1" - "1" Factory_Type
Station "1" -- "1" Station_Type
Factory "1" -- "1..*" Plant_Floor
Plant_Floor "1" -- "1..*" Station
Station "1" -- "1" Industry_Type
Industry_Type "1" -- "1..*" Operation
Product "1" -- "1..*" Operation
Production_Plan "1" -- "1..*" Order
Customer "1" -- "1..*" Order
Category_Customer "1" -- "1..*" Customer
Product "1" -- "1..*" Product_Variant
Order "1" -- "1..*" Production_Order
Production_Order "1" -- "1..*" Product

@enduml