@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0
hide circle
hide methods

class Customer {
    NIF
    Name
    Address
    Mobile_number
    Email
    typeID
    Country_ID
}

class Product {
    Product_ID
    Product_Name
    Product_Description
    Factory_Plant_ID
    Market_Demand
    Optimization
    Production_Cost
    Flexibility
    Family_ID
}

class Factory {
    Factory_Plant_ID
    Safety
    Efficiency
    Space
}

class Factory_Type {
    Type
}

class Raw_Material {
    Raw_Material_ID
    Raw_Material_Name
}

class Plant_Floor {
    Plant_Floor_ID
}

class Station {
    Workstation_ID
    Workstation_Name
    Workstation_Description
}

class Station_Type {
    Workstation_Type_ID
    Workstation_Type
}

class Industry_Type {
    Type_Industry_ID
    Type_Industry
}

class Operation {
    Manufacturing_Operation_ID
    Operation_Description
}

class Production_Plan {
    Product_Planing_ID
    Product_Plan_Start_Date
    Product_Plan_End_Date
}

class Order {
    Customer_Order_ID
    Order_Date
    Delivery_Date
    Location
}

class Product_Family {
    Family_ID
    Family_Description
}

class Production_Order {
    Order_ID
    Product_ID
    Quantity_Ordered
}

Customer "1" -- "0..*" Order
Order "1" -- "0..*" Production_Order
Factory "1" - "1" Factory_Type
Station "1" -- "1" Station_Type
Factory "1" -- "1..*" Plant_Floor
Plant_Floor "1" -- "1..*" Station
Station "1" -- "1" Industry_Type
Industry_Type "1" -- "1..*" Operation
Product "1" -- "1" Product_Family
Product "1" -- "1..*" Operation
Production_Plan "1" -- "0..*" Order
Production_Order "1" -- "1" Product
Production_Order "1" -- "0..*" Raw_Material

@enduml
